/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_matrix.check" instead.
 */

#include <check.h>

#include "../s21_matrix.h"

START_TEST(create_matrix_valid) {
  matrix_t A = {0};
  ck_assert_int_eq(s21_create_matrix(2, 2, &A), OK);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(create_matrix_invalid_negative_1) {
  matrix_t A = {0};
  ck_assert_int_eq(s21_create_matrix(-2, 2, &A), INCORRECT_MATRIX);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(create_matrix_invalid_negative_2) {
  matrix_t A = {0};
  ck_assert_int_eq(s21_create_matrix(2, -2, &A), INCORRECT_MATRIX);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(create_matrix_invalid_negative_null) {
  ck_assert_int_eq(s21_create_matrix(2, 2, NULL), INCORRECT_MATRIX);
}
END_TEST

START_TEST(eq_matrix_valid) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }

  matrix_t B = {0};
  s21_create_matrix(2, 2, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      B.matrix[i][j] = i + j;
    }
  }

  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_invalid_1) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&A, NULL), FAILURE);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(eq_matrix_invalid_2) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t B = {0};
  s21_create_matrix(3, 5, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      B.matrix[i][j] = i + j;
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_invalid_3) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t B = {0};
  s21_create_matrix(2, 2, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      B.matrix[i][j] = i + j + 3;
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(sum_matrix_valid) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }

  matrix_t B = {0};
  s21_create_matrix(2, 2, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      B.matrix[i][j] = i + j;
    }
  }
  matrix_t result = {0};
  matrix_t valid_result = {0};
  s21_create_matrix(2, 2, &valid_result);
  valid_result.matrix[0][0] = 0;
  valid_result.matrix[0][1] = 2;
  valid_result.matrix[1][0] = 2;
  valid_result.matrix[1][1] = 4;
  ck_assert_int_eq(s21_sum_matrix(&A, &B, &result), OK);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_double_eq(result.matrix[i][j], valid_result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&valid_result);
}
END_TEST

START_TEST(sum_matrix_invalid_1) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }

  matrix_t result = {0};
  ck_assert_int_eq(s21_sum_matrix(&A, NULL, &result), INCORRECT_MATRIX);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(sum_matrix_invalid_2) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t B = {0};
  s21_create_matrix(3, 5, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t result = {0};
  ck_assert_int_eq(s21_sum_matrix(&A, &B, &result), CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(sub_matrix_valid) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }

  matrix_t B = {0};
  s21_create_matrix(2, 2, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      B.matrix[i][j] = i + j;
    }
  }
  matrix_t result = {0};
  matrix_t valid_result = {0};
  s21_create_matrix(2, 2, &valid_result);
  valid_result.matrix[0][0] = 0;
  valid_result.matrix[0][1] = 0;
  valid_result.matrix[1][0] = 0;
  valid_result.matrix[1][1] = 0;
  ck_assert_int_eq(s21_sub_matrix(&A, &B, &result), OK);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_double_eq(result.matrix[i][j], valid_result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&valid_result);
}
END_TEST

START_TEST(sub_matrix_invalid_1) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }

  matrix_t result = {0};
  ck_assert_int_eq(s21_sub_matrix(&A, NULL, &result), INCORRECT_MATRIX);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(sub_matrix_invalid_2) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t B = {0};
  s21_create_matrix(3, 5, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t result = {0};
  ck_assert_int_eq(s21_sub_matrix(&A, &B, &result), CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(mult_number_valid) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }

  matrix_t result = {0};
  matrix_t valid_result = {0};
  s21_create_matrix(2, 2, &valid_result);
  valid_result.matrix[0][0] = 0;
  valid_result.matrix[0][1] = 0.5;
  valid_result.matrix[1][0] = 0.5;
  valid_result.matrix[1][1] = 1;
  ck_assert_int_eq(s21_mult_number(&A, 0.5, &result), OK);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_double_eq(result.matrix[i][j], valid_result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&valid_result);
}
END_TEST

START_TEST(mult_number_invalid_1) {
  matrix_t result = {0};
  ck_assert_int_eq(s21_mult_number(NULL, 0, &result), INCORRECT_MATRIX);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(mult_matrix_valid) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j;
    }
  }
  matrix_t B = {0};
  s21_create_matrix(2, 2, &B);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      B.matrix[i][j] = i + j;
    }
  }
  matrix_t result = {0};
  matrix_t valid_result = {0};
  s21_create_matrix(2, 2, &valid_result);
  valid_result.matrix[0][0] = 1;
  valid_result.matrix[0][1] = 2;
  valid_result.matrix[1][0] = 2;
  valid_result.matrix[1][1] = 5;
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), OK);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_double_eq(result.matrix[i][j], valid_result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&valid_result);
}
END_TEST

START_TEST(mult_matrix_invalid_1) {
  matrix_t result = {0};
  ck_assert_int_eq(s21_mult_matrix(NULL, NULL, &result), INCORRECT_MATRIX);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(mult_matrix_invalid_2) {
  matrix_t result = {0};
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(3, 5, &A);
  s21_create_matrix(4, 6, &B);
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), CALCULATION_ERROR);
  s21_remove_matrix(&result);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(transpose_valid) {
  matrix_t A = {0};
  s21_create_matrix(2, 2, &A);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      A.matrix[i][j] = i + j + 3 * j;
    }
  }
  matrix_t result = {0};
  matrix_t valid_result = {0};
  s21_create_matrix(2, 2, &valid_result);
  valid_result.matrix[0][0] = 0;
  valid_result.matrix[0][1] = 1;
  valid_result.matrix[1][0] = 4;
  valid_result.matrix[1][1] = 5;
  ck_assert_int_eq(s21_transpose(&A, &result), OK);
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      ck_assert_double_eq(result.matrix[i][j], valid_result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&valid_result);
}
END_TEST

START_TEST(transpose_invalid) {
  matrix_t result = {0};
  ck_assert_int_eq(s21_transpose(NULL, &result), INCORRECT_MATRIX);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(determinant_valid) {
  matrix_t A = {0};
  double determinant = 0.0f;
  s21_create_matrix(3, 3, &A);
  double cur = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      A.matrix[i][j] = cur;
      cur++;
    }
  }
  ck_assert_int_eq(s21_determinant(&A, &determinant), OK);
  ck_assert_double_eq(determinant, 0);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(boundary_determinant_valid) {
  matrix_t A = {0};
  s21_create_matrix(1, 1, &A);
  double determinant = 0;
  ck_assert_int_eq(s21_determinant(&A, &determinant), OK);
  ck_assert_double_eq(determinant, 1);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_invalid_1) {
  double determinant = 0;
  ck_assert_int_eq(s21_determinant(NULL, &determinant), INCORRECT_MATRIX);
}
END_TEST

START_TEST(determinant_invalid_2) {
  double determinant = 0;
  matrix_t A;
  s21_create_matrix(3, 5, &A);
  ck_assert_int_eq(s21_determinant(&A, &determinant), CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(calc_complements_valid) {
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  matrix_t result;
  s21_create_matrix(3, 3, &result);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 4;
  A.matrix[1][2] = 2;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = 2;
  A.matrix[2][2] = 1;
  matrix_t B;
  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 10;
  B.matrix[0][2] = -20;
  B.matrix[1][0] = 4;
  B.matrix[1][1] = -14;
  B.matrix[1][2] = 8;
  B.matrix[2][0] = -8;
  B.matrix[2][1] = -2;
  B.matrix[2][2] = 4;
  ck_assert_int_eq(s21_calc_complements(&A, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &B), SUCCESS);
}
END_TEST

START_TEST(calc_complements_invalid) {
  ck_assert_int_eq(s21_calc_complements(NULL, NULL), INCORRECT_MATRIX);
}
END_TEST

START_TEST(inverse_valid) {
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  matrix_t result;
  s21_create_matrix(3, 3, &result);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  matrix_t B;
  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 1;
  B.matrix[0][1] = -1;
  B.matrix[0][2] = 1;
  B.matrix[1][0] = -38;
  B.matrix[1][1] = 41;
  B.matrix[1][2] = -34;
  B.matrix[2][0] = 27;
  B.matrix[2][1] = -29;
  B.matrix[2][2] = 24;
  ck_assert_int_eq(s21_inverse_matrix(&A, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &B), SUCCESS);
}
END_TEST

START_TEST(inverse_invalid_1) {
  matrix_t result;
  ck_assert_int_eq(s21_inverse_matrix(NULL, &result), INCORRECT_MATRIX);
}
END_TEST

START_TEST(inverse_invalid_2) {
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 4;
  A.matrix[1][1] = 5;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = 7;
  A.matrix[2][1] = 8;
  A.matrix[2][2] = 9;
  matrix_t result;
  ck_assert_int_eq(s21_inverse_matrix(&A, &result), CALCULATION_ERROR);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, create_matrix_valid);
  tcase_add_test(tc1_1, create_matrix_invalid_negative_1);
  tcase_add_test(tc1_1, create_matrix_invalid_negative_2);
  tcase_add_test(tc1_1, create_matrix_invalid_negative_null);

  tcase_add_test(tc1_1, eq_matrix_valid);
  tcase_add_test(tc1_1, eq_matrix_invalid_1);
  tcase_add_test(tc1_1, eq_matrix_invalid_2);
  tcase_add_test(tc1_1, eq_matrix_invalid_3);

  tcase_add_test(tc1_1, sum_matrix_valid);
  tcase_add_test(tc1_1, sum_matrix_invalid_1);
  tcase_add_test(tc1_1, sum_matrix_invalid_2);

  tcase_add_test(tc1_1, sub_matrix_valid);
  tcase_add_test(tc1_1, sub_matrix_invalid_1);
  tcase_add_test(tc1_1, sub_matrix_invalid_2);

  tcase_add_test(tc1_1, mult_number_valid);
  tcase_add_test(tc1_1, mult_number_invalid_1);

  tcase_add_test(tc1_1, mult_matrix_valid);
  tcase_add_test(tc1_1, mult_matrix_invalid_1);
  tcase_add_test(tc1_1, mult_matrix_invalid_2);

  tcase_add_test(tc1_1, transpose_valid);
  tcase_add_test(tc1_1, transpose_invalid);

  tcase_add_test(tc1_1, determinant_valid);
  tcase_add_test(tc1_1, boundary_determinant_valid);
  tcase_add_test(tc1_1, determinant_invalid_1);
  tcase_add_test(tc1_1, determinant_invalid_2);

  tcase_add_test(tc1_1, calc_complements_valid);
  tcase_add_test(tc1_1, calc_complements_invalid);

  tcase_add_test(tc1_1, inverse_valid);
  tcase_add_test(tc1_1, inverse_invalid_1);
  tcase_add_test(tc1_1, inverse_invalid_2);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
